### PR TITLE
wait for new packets on the agent socket after the handler is invoked…

### PR DESCRIPTION
**Pull request by pfy**
wait for new data on the socket after the handler is called.
ruby net::ssh keeps the agent connection open, but the secretive agent closes the connection :( 
this fixes https://github.com/maxgoedjen/secretive/issues/244

### CODE REVIEW

**Comment by maxgoedjen** [comment]
Hey @pfy, thanks for the fix! This looks correct to me on its face but lemme test it a bit to make sure it doesn't break any other cases.

**Comment by maxgoedjen** [comment]
Also, any chance you have a test script for this you could share?

**Comment by pfy** [comment]
Hi @maxgoedjen,
there is a test script in the bug report (in ruby)
```ruby
require 'net/ssh'
Net::SSH.start('github.com','git',:verbose => :debug) do |ssh|
output = ssh.exec!("hostname")
puts output
end
```

This fails without the mr and works with the MR.

**Comment by maxgoedjen** [comment]
Fantastic thanks 🙏

**Comment by pfy** [comment]
@maxgoedjen how can i help you to get this pr merged ? what is still missing ?

**Comment by maxgoedjen** [comment]
@pfy sorry nothing, just slipped my mind. Giving it a test now.

**Comment by maxgoedjen** [comment]
@pfy tested it out with a simple SSH command and it looks as though it may cause an infinite loop. Can you take a look?

https://user-images.githubusercontent.com/342665/144175353-69d77dbd-2500-4953-9110-bd14ed76ac94.mov

**Comment by maxgoedjen** [comment]
I _think_ this is working: https://github.com/maxgoedjen/secretive/pull/270
Give it a go and let me know if it works for you.

**Comment by pfy** [comment]
@maxgoedjen this PR works for me. How can I help you to get it merged ?

**Comment by maxgoedjen** [comment]
@pfy sorry this kinda fell of my radar post-vacation. It's looking good in my testing, I'll create a test build that I'll run for a while (would appreciate if you could test it out for a while until it's released as well).  Thanks again for fixing this :)

**Review by maxgoedjen — APPROVED** [review]

**Comment by maxgoedjen** [comment]
@pfy I think you'll need to update this with changes from the base, but should be all good to go then.

**Comment by pfy** [comment]
ok, i will do that, thanks @maxgoedjen

**Pull request merged**
