### PR TITLE
Add German Localization 🇩🇪 

### PR DESCRIPTION
**Pull request by moritzsternemann**
Thanks for making this awesome app! 🙌 

Translating technical terms like "secret" is always a bit tricky so kept this one as I think it makes sense for a technical tool like Secretive. Would be awesome if another native speaker could give some feedback!

### CODE REVIEW

**Comment by maxgoedjen** [comment]
@moritzsternemann awesome, thanks so much for doing this!

WRT the "secret" naming – it might be easier to translate it as "key?" I use that and secret somewhat interchangeably in English, but I'm not especially attached to it as a "brand" or anything.

**Comment by maxgoedjen** [comment]
Anyway I'll set this to merge as-is, if you feel like translating "secret" to something else will be clearer I'll also be happy to merge any followups to that effect. Thanks again!

**Comment by moritzsternemann** [comment]
Sorry I left this hanging for so long. Also thought about using "key" instead of secret but there's places where "key" doesn't make much sense either.

I think we are good for now and we can still re-evaluate when there's additional strings to translate. Thanks for merging!

**Comment by EmmyGraugans** [comment]
Thanks to @moritzsternemann for providing the translation.

(Very) minor gripe: "Großschreibung ist Glücksache". When things get added (and only then, no need to change it right now), a lot of verbs and adjectives should probably start with a lowercase letter.

Regarding the discussion above re: "key" or "secret": why not "Schlüssel", which is the german word for both? At least in one place the word Schlüssel is already used. Again, nothing that is urgent to change.

**Pull request merged**
