### PR TITLE
Configure ssh directly instead of setting environment variable

### LINKED ISSUE #194: Consider configuring ssh directly instead of setting environment variable?
Hey, this project is great and it has been a time saver. When I set it up, I ended up configuring ssh directly (via adding IdentityAgent to ~.ssh/config) so I didn't have to worry about editor integration or shell differences.

Is this an approach that you've found to be a problem or would a patch to suggest this approach instead of shell variables be welcome?

### PR DESCRIPTION
**Pull request by lavalleeale**
Fixes #194

### CODE REVIEW

**Comment by maxgoedjen** [comment]
Just to double check, you've tested this and it's working well? May make sense to just get rid of the rest if that's the case (will have to see if there's any compelling reasons to keep the other way).

**Comment by lavalleeale** [comment]
I have checked it with bash and zsh, but not yet with fish

**Comment by maxgoedjen** [comment]
Sweet. The only _obvious_ "downside" I can see is it's not supported for older versions of ssh but those versions are older than what secretive supports anyway 🤷‍♀️

**Comment by lavalleeale** [comment]
It also does work for apps that don’t have a terminal, like vscode, which is nice

**Comment by lavalleeale** [comment]
I actually did run into one issue with it, because it replaces Secretive globally you cannot use normal keys anywhere, nor will the keys show in `ssh-add -l`

**Comment by ciaranmcnulty** [comment]
Thanks for this; I was able to use this to get Secretive working with my IDE 👍

**Comment by maxgoedjen** [comment]
@lavalleeale sorry this kinda fell off my radar 🤦‍♂️. Thanks for doing this, looks great and clearly helping people already 🙏

**Pull request merged**
