### PR TITLE
Keep socket open when possible

### LINKED ISSUE #244: secretive does not work as agent for ruby net::ssh
The ruby ssh implementation, net::ssh, does not seem to work with secretive.

I don't know how to get the debug log from the side of secretive, console logs some things for normal operation (ssh) but is empty for the ruby test program. I tried to enable debug logging for the secretive agent without success.
```
sudo  log config  --mode "level:debug" --subsystem com.maxgoedjen.Secretive.SecretAgent
```

minimal program:
```ruby
require 'net/ssh'
Net::SSH.start('github.com','git',:verbose => :debug) do |ssh|
output = ssh.exec!("hostname")
puts output
end
```

output
```
D, [2021-10-07T23:53:09.042279 #34730] DEBUG -- net.ssh.transport.session[3feac44466c0]: establishing connection to github.com:22
D, [2021-10-07T23:53:09.052789 #34730] DEBUG -- net.ssh.transport.session[3feac44466c0]: connection established
I, [2021-10-07T23:53:09.052841 #34730]  INFO -- net.ssh.transport.server_version[3fead4d094c8]: negotiating protocol version
D, [2021-10-07T23:53:09.052858 #34730] DEBUG -- net.ssh.transport.server_version[3fead4d094c8]: local is `SSH-2.0-Ruby/Net::SSH_6.1.0 x86_64-darwin20'
D, [2021-10-07T23:53:09.223403 #34730] DEBUG -- net.ssh.transport.server_version[3fead4d094c8]: remote is `SSH-2.0-babeld-7cdf2150'
I, [2021-10-07T23:53:09.226270 #34730]  INFO -- net.ssh.transport.algorithms[3fead4d0876c]: sending KEXINIT
D, [2021-10-07T23:53:09.226464 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 0 type 20 len 748
D, [2021-10-07T23:53:09.226577 #34730] DEBUG -- socket[3fead4d09c48]: sent 752 bytes
D, [2021-10-07T23:53:09.226690 #34730] DEBUG -- socket[3fead4d09c48]: read 792 bytes
D, [2021-10-07T23:53:09.226754 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 0 type 20 len 788
I, [2021-10-07T23:53:09.226789 #34730]  INFO -- net.ssh.transport.algorithms[3fead4d0876c]: got KEXINIT from server
I, [2021-10-07T23:53:09.226855 #34730]  INFO -- net.ssh.transport.algorithms[3fead4d0876c]: negotiating algorithms
D, [2021-10-07T23:53:09.226928 #34730] DEBUG -- net.ssh.transport.algorithms[3fead4d0876c]: negotiated:
* kex: ecdh-sha2-nistp521
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512-etm@openssh.com
* hmac_server: hmac-sha2-512-etm@openssh.com
* compression_client: none
* compression_server: none
* language_client:
* language_server:
D, [2021-10-07T23:53:09.226962 #34730] DEBUG -- net.ssh.transport.algorithms[3fead4d0876c]: exchanging keys
D, [2021-10-07T23:53:09.227643 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 1 type 30 len 148
D, [2021-10-07T23:53:09.227708 #34730] DEBUG -- socket[3fead4d09c48]: sent 152 bytes
D, [2021-10-07T23:53:09.326671 #34730] DEBUG -- socket[3fead4d09c48]: read 704 bytes
D, [2021-10-07T23:53:09.326755 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 1 type 31 len 700
D, [2021-10-07T23:53:09.327583 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 2 type 21 len 20
D, [2021-10-07T23:53:09.327634 #34730] DEBUG -- socket[3fead4d09c48]: sent 24 bytes
D, [2021-10-07T23:53:09.327726 #34730] DEBUG -- socket[3fead4d09c48]: read 16 bytes
D, [2021-10-07T23:53:09.327770 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 2 type 21 len 12
D, [2021-10-07T23:53:09.327937 #34730] DEBUG -- net.ssh.authentication.session[3feac447aefc]: beginning authentication of `git'
D, [2021-10-07T23:53:09.327977 #34730] DEBUG -- socket[3fead4d09c48]: using encrypt-then-mac
D, [2021-10-07T23:53:09.328024 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 3 type 5 len 32
D, [2021-10-07T23:53:09.328058 #34730] DEBUG -- socket[3fead4d09c48]: sent 100 bytes
D, [2021-10-07T23:53:09.424720 #34730] DEBUG -- socket[3fead4d09c48]: read 100 bytes
D, [2021-10-07T23:53:09.424838 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 3 type 6 len 32
D, [2021-10-07T23:53:09.424924 #34730] DEBUG -- net.ssh.authentication.session[3feac447aefc]: trying none
D, [2021-10-07T23:53:09.424986 #34730] DEBUG -- socket[3fead4d09c48]: using encrypt-then-mac
D, [2021-10-07T23:53:09.425023 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 4 type 50 len 48
D, [2021-10-07T23:53:09.425066 #34730] DEBUG -- socket[3fead4d09c48]: sent 116 bytes
D, [2021-10-07T23:53:09.513916 #34730] DEBUG -- socket[3fead4d09c48]: read 100 bytes
D, [2021-10-07T23:53:09.514017 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 4 type 51 len 32
D, [2021-10-07T23:53:09.514060 #34730] DEBUG -- net.ssh.authentication.session[3feac447aefc]: allowed methods: publickey
D, [2021-10-07T23:53:09.514095 #34730] DEBUG -- net.ssh.authentication.methods.none[3feacc4299f0]: none failed
D, [2021-10-07T23:53:09.514124 #34730] DEBUG -- net.ssh.authentication.session[3feac447aefc]: trying publickey
D, [2021-10-07T23:53:09.514232 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: connecting to ssh-agent
D, [2021-10-07T23:53:09.514321 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: sending agent request 1 len 47
D, [2021-10-07T23:53:09.514468 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: received agent packet 5 len 1
D, [2021-10-07T23:53:09.514497 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: sending agent request 11 len 0
D, [2021-10-07T23:53:09.514677 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: received agent packet 12 len 136
D, [2021-10-07T23:53:09.514888 #34730] DEBUG -- net.ssh.authentication.methods.publickey[3feacc42853c]: trying publickey (48:59:0f:59:a3:6f:6c:6a:f5:fc:03:0d:46:0e:44:1f)
D, [2021-10-07T23:53:09.514946 #34730] DEBUG -- socket[3fead4d09c48]: using encrypt-then-mac
D, [2021-10-07T23:53:09.514982 #34730] DEBUG -- socket[3fead4d09c48]: queueing packet nr 5 type 50 len 176
D, [2021-10-07T23:53:09.515024 #34730] DEBUG -- socket[3fead4d09c48]: sent 244 bytes
D, [2021-10-07T23:53:09.628173 #34730] DEBUG -- socket[3fead4d09c48]: read 212 bytes
D, [2021-10-07T23:53:09.628287 #34730] DEBUG -- socket[3fead4d09c48]: received packet nr 5 type 60 len 144
D, [2021-10-07T23:53:09.628387 #34730] DEBUG -- net.ssh.authentication.agent[3feacc4283fc]: sending agent request 13 len 355
Traceback (most recent call last):
       16: from (irb):2
       15: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh.rb:255:in `start'
       14: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `authenticate'
       13: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:72:in `each'
       12: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/session.rb:86:in `block in authenticate'
       11: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
       10: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:114:in `each_identity'
        9: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:114:in `each'
        8: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:122:in `block in each_identity'
        7: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:20:in `block in authenticate'
        6: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/methods/publickey.rb:62:in `authenticate_with'
        5: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/key_manager.rb:180:in `sign'
        4: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:153:in `sign'
        3: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:220:in `send_and_wait'
        2: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:203:in `send_packet'
        1: from /Users/pfy/.rvm/gems/ruby-2.6.6/gems/net-ssh-6.1.0/lib/net/ssh/authentication/agent.rb:203:in `send'
Errno::EPIPE (Broken pipe - send(2))
```

### PR DESCRIPTION
**Pull request by maxgoedjen**
Fixes #244

### CODE REVIEW

**Comment by pfy** [comment]
@maxgoedjen thanks for this solution. 
it would certainly work,  for my usecase. But if somebody only requests the identites via ssh-add -l, the socket would keep spinning.

The safer way to do this is the following:
If availableData has a zero length in the NSFileHandleDataAvailable notification, the socket is closed.

i updated my PR and it seems to work.

**Comment by maxgoedjen** [comment]
Hm swear I tried something like that and it didn't work properly for one of those cases. You tried just vanilla command line ssh?

**Comment by pfy** [comment]
yes 
My first try, when i called availableData in the notification callback didn't work as well.
it seems that calling availableData seeks the stream and consumes the data. The documentation from apple could be improved there.

**Comment by maxgoedjen** [comment]
Yeah It's def

**Pull request closed without merging**
